fixes #14174 - content-view add-repository should require user to provide repo info
This commit addresses the issue that if the user was attempting to add
a repository to a content view, but did not specify the repository parameters,
the command would succeed indicating "The repository has been associated".

The update behavior is:

hammer> content-view add-repository --name zoo2 --organization-id 3
Could not add repository:
  Error: At least one of options --repository-id, --repository is required